# ~/.config/yazi/yazi.toml
[mgr]
# 是否显示隐藏文件
show_hidden = true
# 默认排序方式
sort_by = "natural"
# 是否使用自然排序（1,2,10而不是1,10,2）
sort_sensitive = false
# 默认布局（右侧显示预览）
layout = "default"
[preview]
# 启用 Kitty 图片预览（如果你用的是 Kitty 终端）
image_previewer = "kitty"
max_width = 100
max_height = 40

# [theme]
# 选择配色方案
# theme = "grub"
